### ISSUE TITLE
AzureData.getDocument() is failed with an error code "unauthorized"

### ISSUE THREAD

**Issue by Raysapps** [Azure/azure-sdk-for-android#410]
**Query/Question**
Calling AzureData.getDocument() is failed with an error code "unauthorized". Could you please advise if  I am missing anything?

Error description:
{"code":"Unauthorized","message":"Required Header authorization is missing. Ensure a valid Authorization token is passed.\r\nActivityId: 8ff03cec-89c1-4692-9d56-fb500c936180, Microsoft.Azure.Documents.Common/2.11.0"}

***Why is this not a Bug or a feature Request?***
May be a bug

**Comment by vcolin7** [comment]
Hi @Raysapps,

I'm not entirely familiar with the older Track 1 library but the first thing that comes to mind is that you might be using the wrong (or malformed) credentials when you call `AzureData.configure()`. I tested locally by passing a malformed master key and got the following:

```json
{"code":"Unauthorized","message":"The input authorization token can't serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. Server used the following payload to sign: 'get\ndbs\ndbs/TestDatabase\nmon, 26 oct 2020 04:15:57 gmt\n\n'\r\nActivityId: 55ac3be6-e16c-44fb-b137-f4ab7d6756e7, Microsoft.Azure.Documents.Common/2.11.0"}
```

If you are using any of the other overloads of the `cofigure()` method make sure to pass the right information.

Additionally, through some trial and error I found that the library might cache some credentials and query results, so I had to uninstall my sample app and install it back again to actually see changes. I'm not entirely sure what are the limits of this, but it wouldn't hurt to try that as well.

**Comment by bsiegel** [comment]
Can you provide a sample that reproduces the issue? (Do not include a real credential though please). We know that other customers are using this library successfully so I would suspect that it's a case of a misconfigured credential but it's hard to say without a sample that reproduces the issue.

**Comment by Raysapps** [comment]
@bsiegel: I am still getting the error. Here is the sample "https://github.com/Raysapps/AzureDataTest". Please verify and advise.

**Comment by bsiegel** [comment]
Thanks for providing the repro, it was very helpful. I'm not able to exactly reproduce the issue you're seeing - I think it's possible that the device is caching a response that may have been returned in the past when no credentials were supplied. Try disabling caching as follows:

```kotlin
        // provide Valid  cosmosDB accountName and accountKey
        val accountKey = "<your-master-account-key>"
        val accountName= "<your-account-name>"

        AzureData.isOfflineDataEnabled = false
        AzureData.configure(this, accountName, accountKey, PermissionMode.All)
```

When I did this, I was able to submit requests to the service but I ran into an additional problem - on my emulator, the Date header was being mis-formatted by the library. Can you please try the above change and let me know if you receive a different error similar to the following?

`{"code":"Unauthorized","message":"The input date header is invalid format. Please pass in RFC 1123 style date format.\r\nActivityId: <some id>, Microsoft.Azure.Documents.Common/2.11.0"}`

**Comment by Raysapps** [comment]
Thank you. The API call was successful on Windows 10 Emulator and  Samsung Galaxy s8, but failed with unauthorized error on Pixel3 Android Version 11. I haven't got any new errors. Please find the images attached of my test results. Hope these are helpful in providing further advice/suggestions.
![emulator](https://user-images.githubusercontent.com/45407360/97375499-19069e00-190f-11eb-9c36-ec22b6ff0713.png)
![Pixel3](https://user-images.githubusercontent.com/45407360/97375502-1ad06180-190f-11eb-92e2-4dfc11a9d0c0.jpg)
![SamSungDevice](https://user-images.githubusercontent.com/45407360/97375508-1c9a2500-190f-11eb-9e40-2f21cf6cf3a4.jpg)

**Comment by bsiegel** [comment]
Okay, thank you - that confirms what I was seeing too, my emulator was also on Android 11. It seems like there is a bug in the AzureCore library that AzureData depends on, specifically [here](https://github.com/Azure/azure-sdk-for-android/blob/Azure.Android/azurecore/src/main/java/com/azure/core/util/DateFormat.kt#L22) - this code is mistakenly using the `ROOT` locale rather than `Locale.US` to format the Date header, and it seems like on newer versions of Android the `ROOT` locale no longer contains month names.

Unfortunately, the library is deprecated and we don't have an upgrade path at present for you. My best recommendation would be to either

1.) Check out the [Azure.Android](https://github.com/Azure/azure-sdk-for-android/tree/Azure.Android) branch of this repo and build your own copies of the AzureCore and AzureData libraries locally, applying the fix mentioned above to `DateFormat.kt` in AzureCore; or

2.) Use the [CosmosDB client library for Java](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-cosmos) in your Android application, which is a much more complete client library but unfortunately it is not designed specifically to work on Android. You can use the example code from [this project](https://github.com/anuchandy/reactor-android/tree/reactor-android-teration) to help, which would allow you to subscribe to the reactive results from the Android UI thread.

**Comment by Raysapps** [comment]
Thank you for the suggestions. I will explore both options and implement in my project.

**Comment by bsiegel** [comment]
Closing this issue as it appears to be inactive. If there are further issues with the Track 1 SDK, please file an issue and we'll make a best effort to assist you.
