### ISSUE TITLE
Add logAndThrow to ClientLogger

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-android#470]
Add the `logAndThrow` methods to the ClientLogger as defined in the guidelines.

**Comment by vcolin7** [comment]
I noticed that even though the Java Guidelines indicate that the `logAndThrow` method should be used so exceptions are not just thrown without being logged, that exact method does not exist in [the ClientLogger class](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/util/logging/ClientLogger.java). Instead, there are methods such as:

* [`logExceptionAsWarning`](https://github.com/Azure/azure-sdk-for-java/blob/29e68f834fc0d0d8ffc890f48be316ff1df4006e/sdk/core/azure-core/src/main/java/com/azure/core/util/logging/ClientLogger.java#L216)
* [`logThrowableAsWarning`](https://github.com/Azure/azure-sdk-for-java/blob/29e68f834fc0d0d8ffc890f48be316ff1df4006e/sdk/core/azure-core/src/main/java/com/azure/core/util/logging/ClientLogger.java#L256)
* [`logExceptionAsError`](https://github.com/Azure/azure-sdk-for-java/blob/29e68f834fc0d0d8ffc890f48be316ff1df4006e/sdk/core/azure-core/src/main/java/com/azure/core/util/logging/ClientLogger.java#L276)
* [`logThrowableAsError`](https://github.com/Azure/azure-sdk-for-java/blob/29e68f834fc0d0d8ffc890f48be316ff1df4006e/sdk/core/azure-core/src/main/java/com/azure/core/util/logging/ClientLogger.java#L293)

I think this is because, unlike conventional Android logging, there are no overloaded methods that allow for passing a `Throwable` to be logged at the desired level, for example `void info(String message)` and `void info(String message, Throwable throwable)`.

Now, none of the Java SDK methods mentioned above throws the `Exception` or `Throwable` itself but they rather return it to let the caller decide what to do with it. I'm not sure if that's an approach I would like to take with Android (although I don't necessarily oppose it).

About the method signature for `logAndThrow`, would we need to provide a log level (`logAndThrow(LogLevel logLevel, Throwable throwable)`)? Would it be better to have one of these for WARNING and one for ERROR (`logAsWarningAndThrow` + `logAsErrorAndThrow`)?

// cc @bsiegel, @anuchandy

**Comment by anuchandy** [comment]
It's possible that Java [guideline](https://azure.github.io/azure-sdk/java_implementation.html#java-logging-log-and-throw) is outdated, if that's the case we should correct it (for java and android) to what client-libs have been following, i.e.

From:
```
if (priority != null && priority < 0) {
    logger.logAndThrow(
        new IllegalArgumentException(
            "'priority' cannot be a negative value. Please specify a zero or positive long value."));
}
```

To:

```
if (priority != null && priority < 0) {
    throw logger.logExceptionAsError(
        new IllegalArgumentException(
            "'priority' cannot be a negative value. Please specify a zero or positive long value."));
}
```

**Comment by anuchandy** [comment]
Confirmed with Srikanta, the guideline needs to be corrected.

**Comment by srnagar** [comment]
Updated the guidelines in this PR - https://github.com/Azure/azure-sdk/pull/2238
