### ISSUE TITLE
Create release pipeline for Android

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-android#475]

**Comment by vcolin7** [comment]
How would this differ from what we do at the moment? Does this issue refer to adding missing pieces or changing the way we do things?

**Comment by bsiegel** [comment]
It's an epic for tracking all of the release processes we need. We have the internal pipelines for releasing, but we don't currently have the automation Java has around bumping versions for example (we should add an issue for this). I've also linked in the Create Auto Release Notes Script issue originally filed by Jon.

**Comment by mitchdenny** [comment]
@benbp we have the release pipelines for Android but they don't participate in version bumping logic, they also don't have some of the eng/common packaging logic (sufficiently different from Java that it isn't directly translatable).

**Comment by JimSuplizio** [comment]
@bsiegel @vcolin7 
The Android release pipelines/tools were [updated](https://github.com/Azure/azure-sdk-for-android/pull/1240) near the end of last year when I had to move them to ESRP release. This included bringing the tools repository more up to date with build tools (it was locked into a version from 2021). Because this uses gradle, and not maven, it wasn't possible to reuse the centralized versioning that we have for Java. @vcolin7 and I chatted about this at the time and there simply aren't enough releases in these pipelines to merit to the amount of work required. If centralized versioning is going to be implemented for Android it would be @vcolin7, not me, doing the work for this, otherwise things are going to remain as they are right now.
